// <auto-generated />
namespace LibrarySystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Initialreleasestate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialreleasestate));
        
        string IMigrationMetadata.Id
        {
            get { return "201710230954168_Initial release state"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
